### ISSUE TITLE
setup_test fails with No such file or directory: 'command line'

### ISSUE THREAD

**Issue by phdye** [Pebaz/nimporter#27]
Python 3.8.2
```py3.8 xps-ne ~/.../examples/setup_test $ python setup.py build
Traceback (most recent call last):
  File "setup.py", line 7, in <module>
    ext_modules=nimporter.build_nim_extensions()
  File "/home/phdyex/.local/lib/python3.8/site-packages/nimporter.py", line 1070, in build_nim_extensions
    ext = cls._build_nim_extension(extension, root)
  File "/home/phdyex/.local/lib/python3.8/site-packages/nimporter.py", line 968, in _build_nim_extension
    return NimCompiler.compile_nim_extension(
  File "/home/phdyex/.local/lib/python3.8/site-packages/nimporter.py", line 465, in compile_nim_extension
    raise NimCompileException(errors[0])
  File "/home/phdyex/.local/lib/python3.8/site-packages/nimporter.py", line 56, in __init__
    with open(nim_module, 'r') as mod:
FileNotFoundError: [Errno 2] No such file or directory: 'command line'
```

**Comment by phdye** [comment]
setup_tests must be clean, without build or nim-extensions sub-directories, for the error to occur.  Executing "python setup.py build" a second time works.  Thanks
