### ISSUE TITLE
[Bug] dynamic module does not define module export function

### ISSUE THREAD

**Issue by knassar702** [Pebaz/nimporter#53]
hello , im trying to run simple nim code inside python script with nimporter but i always got an error about importing error from GCC 

* nscript.nim

```nim
proc main() =
   echo "Hello World From NIm"
```

* test.py

```python
import nimporter
import nscript

print("Word :D")
```

<details>
  <summary> <samp>&#9776; Error</samp></summary>

```
$ python test.py

gcc: fatal error: no input files
compilation terminated.
Traceback (most recent call last):
  File "/home/knassar702/.local/lib/python3.9/site-packages/nimporter.py", line 863, in __validate_spec
    util.module_from_spec(spec)
  File "<frozen importlib._bootstrap>", line 565, in module_from_spec
  File "<frozen importlib._bootstrap_external>", line 1173, in create_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
ImportError: dynamic module does not define module export function (PyInit_nscript)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/knassar702/nim_test/test.py", line 2, in <module>
    import nscript
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 982, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 925, in _find_spec
  File "/home/knassar702/.local/lib/python3.9/site-packages/nimporter.py", line 1150, in find_spec
    return Nimporter.import_nim_code(fullname, path, library=False)
  File "/home/knassar702/.local/lib/python3.9/site-packages/nimporter.py", line 841, in import_nim_code
    cls.__validate_spec(spec)
  File "/home/knassar702/.local/lib/python3.9/site-packages/nimporter.py", line 909, in __validate_spec
    raise NimporterException(error_message) from import_error
nimporter.NimporterException: Error importing /home/knassar702/nim_test/__pycache__/nscript.so
Error Message:

    dynamic module does not define module export function (PyInit_nscript)

Python Version:

    3.9.6 (default, Jun 30 2021, 15:31:20) [GCC 11.1.0]

Nim Version:

    Nim Compiler Version 1.4.8 [Linux: amd64]

CC Version:

    <Error getting version>

Installed CCs:

    {'gcc': PosixPath('/usr/bin/gcc')}

Please help improve Nimporter by opening a bug report at: https://github.com/Pebaz/nimporter/issues/new and submit the above information along with your description of the issue.


```

</details>

### Env
* OS : Arch Linux (64)
* Nim Compiler : 1.4.8 
* Python : 3.9.6

**Comment by Pebaz** [comment]
You gotta use the exportpy:

```nim
# mymodule.nim - file name should match the module name you're going to import from python
import nimpy

proc greet(name: string): string {.exportpy.} =
  return "Hello, " & name & "!"
```

Lookup the docs for [Nimpy](https://github.com/yglukhov/nimpy) as Nimporter just makes Nimpy modules easier to import.

**Comment by knassar702** [comment]
thanks for your answer , its work :D
