### ISSUE TITLE
Cannot compile even if GCC is found

### ISSUE THREAD

**Issue by ThibaudMZN** [Pebaz/nimporter#63]
Hi, 
I'm trying to use nimporter in Windows10 and I'm getting the following error:

```
Traceback (most recent call last):
  File "c:\users\thiba\appdata\local\programs\python\python38\lib\site-packages\nimporter.py", line 979, in __validate_spec
    util.module_from_spec(spec)
  File "<frozen importlib._bootstrap>", line 556, in module_from_spec
  File "<frozen importlib._bootstrap_external>", line 1101, in create_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
ImportError: DLL load failed while importing engine: %1 is not a valid Win32 application.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\thiba\AppData\Local\Programs\Python\Python38\Scripts\pyxalchemy-script.py", line 11, in <module>
    load_entry_point('pyxalchemy', 'console_scripts', 'pyxalchemy')()
  File "c:\users\thiba\appdata\local\programs\python\python38\lib\site-packages\pkg_resources\__init__.py", line 489, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "c:\users\thiba\appdata\local\programs\python\python38\lib\site-packages\pkg_resources\__init__.py", line 2852, in load_entry_point
    return ep.load()
  File "c:\users\thiba\appdata\local\programs\python\python38\lib\site-packages\pkg_resources\__init__.py", line 2443, in load
    return self.resolve()
  File "c:\users\thiba\appdata\local\programs\python\python38\lib\site-packages\pkg_resources\__init__.py", line 2449, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "d:\src\python_projects\pyxalchemy\pyxalchemy\game.py", line 12, in <module>
    from . import engine
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 914, in _find_spec
  File "c:\users\thiba\appdata\local\programs\python\python38\lib\site-packages\nimporter.py", line 1269, in find_spec
    return Nimporter.import_nim_code(fullname, path, library=False)
  File "c:\users\thiba\appdata\local\programs\python\python38\lib\site-packages\nimporter.py", line 957, in import_nim_code
    cls.__validate_spec(spec)
  File "c:\users\thiba\appdata\local\programs\python\python38\lib\site-packages\nimporter.py", line 1025, in __validate_spec
    raise NimporterException(error_message) from import_error
nimporter.NimporterException: Error importing D:\src\Python_Projects\Pyxalchemy\pyxalchemy\__pycache__\engine.pyd
Error Message:

    DLL load failed while importing engine: %1 is not a valid Win32 application.

Python Version:

    3.8.1 (tags/v3.8.1:1b293b6, Dec 18 2019, 23:11:46) [MSC v.1916 64 bit (AMD64)]

Nim Version:

    Nim Compiler Version 1.6.4 [Windows: i386]

CC Version:

    <No compatible C compiler installed>

Installed CCs:

    {'gcc': WindowsPath('C:/tools/mingw-w64/mingw32/bin/gcc.EXE')}

Please help improve Nimporter by opening a bug report at: https://github.com/Pebaz/nimporter/issues/new and submit the above information along with your description of the issue.
```

**Comment by Pebaz** [comment]
Can you post the main `.nim` module?

The main thing I'm looking for is that `{.exportpy.}` is used.

Also, it looks like Nimporter wasn't able to find a C compiler installed. Make sure there aren't competing C compilers installed on your PATH.

One last thing, I *highly recommend not using GCC* with an MSVC version of Python. Although this pairing may work on paper, in practice there will be *many* odd incompatibilities to account for.

One thing to note is that in future versions of Nimporter, I'm working on actually disallowing C compilers that are different than the C compiler used to compile Python itself because of this issue.

If you can post more info (build output, etc.) I'll help in any way I can! 🙂
