### ISSUE TITLE
nimporter.NimporterException: Error importing faster_than_requests.pyd

### ISSUE THREAD

**Issue by Nqndi** [Pebaz/nimporter#70]
`std/db_sqlite(184, 1) Warning: Circular dependency detected. 'codeReordering' pragma may not be able to reorder some nodes properly [User]
ws.nim(329, 32) Warning: conversion to enum with holes is unsafe: Opcode(b0 and 0x0000000F) [HoleEnumConv]
nimpy.nim(557, 32) Warning: Cannot prove that 'arg0timeout' is initialized. This will become a compile time error in the future. [ProveInit]
faster_than_requests.nim(293, 132) Warning: Deprecated since v1.5; Use auto instead.; any is deprecated [Deprecated]
faster_than_requests.nim(298, 101) Warning: Deprecated since v1.5; Use auto instead.; any is deprecated [Deprecated]
Traceback (most recent call last):
  File "C:\Users\Nandi\AppData\Local\Programs\Python\Python39\lib\site-packages\nimporter.py", line 979, in __validate_spec
    util.module_from_spec(spec)
  File "<frozen importlib._bootstrap>", line 565, in module_from_spec
  File "<frozen importlib._bootstrap_external>", line 1108, in create_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
ImportError: DLL load failed while importing faster_than_requests: The specified module could not be found.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\Nandi\Desktop\python\speed.py", line 1, in <module>
    import faster_than_requests
  File "C:\Users\Nandi\AppData\Local\Programs\Python\Python39\lib\site-packages\faster_than_requests\__init__.py", line 7, in <module>
    from . faster_than_requests import *
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 982, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 925, in _find_spec
  File "C:\Users\Nandi\AppData\Local\Programs\Python\Python39\lib\site-packages\nimporter.py", line 1269, in find_spec
    return Nimporter.import_nim_code(fullname, path, library=False)
  File "C:\Users\Nandi\AppData\Local\Programs\Python\Python39\lib\site-packages\nimporter.py", line 957, in import_nim_code
    cls.__validate_spec(spec)
  File "C:\Users\Nandi\AppData\Local\Programs\Python\Python39\lib\site-packages\nimporter.py", line 1025, in __validate_spec
    raise NimporterException(error_message) from import_error
nimporter.NimporterException: Error importing C:\Users\Nandi\AppData\Local\Programs\Python\Python39\Lib\site-packages\faster_than_requests\__pycache__\faster_than_requests.pyd
Error Message:

    DLL load failed while importing faster_than_requests: The specified module could not be found.

Python Version:

    3.9.0 (tags/v3.9.0:9cf6752, Oct  5 2020, 15:34:40) [MSC v.1927 64 bit (AMD64)]

Nim Version:

    Nim Compiler Version 1.6.6 [Windows: amd64]

CC Version:

    vccUndefined: C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Auxiliary\Build\vcvarsall.bat

Installed CCs:

    {'msc': WindowsPath('C:/nim/bin/vccexe.EXE'), 'clang': WindowsPath('C:/Users/Nandi/AppData/Local/Nuitka/Nuitka/gcc/x86_64/10.2.0-11.0.0-8.0.0-r5/mingw64/bin/clang.EXE'), 'gcc': WindowsPath('C:/Users/Nandi/AppData/Local/Nuitka/Nuitka/gcc/x86_64/10.2.0-11.0.0-8.0.0-r5/mingw64/bin/gcc.EXE')}

Please help improve Nimporter by opening a bug report at: https://github.com/Pebaz/nimporter/issues/new and submit the above information along with your description of the issue.`

**Comment by Pebaz** [comment]
Thank you for opening a bug report. Can you post a code example to reproduce this?

**Comment by Nqndi** [comment]
I installed faster_than_requests on python 3.9, and when I try to import it using import faster_than_requests, I get this error.

**Comment by Nqndi** [comment]
It compiles just fine, and I can import it inside test.py

**Comment by juancarlospaco** [comment]
Awesome!, I think is something missing from Nim and Python ecosystems, 
Rust-Python has its lib to do this, but not Nim-Python, this is a great tool.

I am interested, I have no time right now and I have to learn the new API from docs,
I can accept pull requests if someone is interested tho...
🙂:+1:

**Comment by Nqndi** [comment]
Do you guys have any idea how to fix this?

**Comment by Pebaz** [comment]
Closing this for now but feel free to open again.
