### ISSUE TITLE
nimporter can't find file on Windows 10

### ISSUE THREAD

**Issue by davidcsisk** [Pebaz/nimporter#75]
Here is a working example to reproduce the problem:

C:\Users\dave.sisk\math_speedup_example>type pmath.py
def fib(n):
    if n == 0:
        return 0
    elif n < 3:
        return 1
    return fib(n - 1) + fib(n - 2)

C:\Users\dave.sisk\math_speedup_example>type nmath.nim
import nimpy

proc fib(n: int): int {.exportpy.} =
    if n == 0:
        return 0
    elif n < 3:
        return 1
    return fib(n-1) + fib(n-2)

C:\Users\dave.sisk\math_speedup_example>type main.py
import nimporter
from time import perf_counter
import nmath  # Nim imports!
import pmath
print('Measuring Python...')
start_py = perf_counter()
for i in range(0, 40):
    print(pmath.fib(i), end=" ")
end_py = perf_counter()

print('\n\nMeasuring Nim...')
start_nim = perf_counter()
for i in range(0, 40):
    print(nmath.fib(i), end=" ")
end_nim = perf_counter()

print('\n---------')
print('Python Elapsed: {:.2f}'.format(end_py - start_py))
print('Nim Elapsed: {:.2f}'.format(end_nim - start_nim))

C:\Users\dave.sisk\math_speedup_example>python main.py
Traceback (most recent call last):
  File "C:\Users\dave.sisk\math_speedup_example\main.py", line 3, in <module>
    import nmath  # Nim imports!
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1002, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 945, in _find_spec
  File "C:\Users\dave.sisk\AppData\Local\Programs\Python\Python310\lib\site-packages\nimporter.py", line 1269, in find_spec
    return Nimporter.import_nim_code(fullname, path, library=False)
  File "C:\Users\dave.sisk\AppData\Local\Programs\Python\Python310\lib\site-packages\nimporter.py", line 944, in import_nim_code
    NimCompiler.compile_nim_code(
  File "C:\Users\dave.sisk\AppData\Local\Programs\Python\Python310\lib\site-packages\nimporter.py", line 705, in compile_nim_code
    cls.check_compile_errors(errors, library, nim_args, output, tmp_cwd, warnings)
  File "C:\Users\dave.sisk\AppData\Local\Programs\Python\Python310\lib\site-packages\nimporter.py", line 492, in check_compile_errors
    raise NimCompileException(errors[0])
nimporter.NimCompileException: Error: unhandled exception: The system cannot find the file specified.

**Comment by davidcsisk** [comment]
This works beautifully on Linux, but returns the "system cannot find the file specified" error on Windows 10. I've tried it on 2 different Windows 10 laptops, so I don't think it's anything specific to the laptop setup.

**Comment by Pebaz** [comment]
Hi @davidcsisk , can you confirm what C compilers you have installed a long with arch info?
Also, please provide Nim version (and arch), Nimble version, Choosenim version, and Python version (and arch)

**Comment by Pebaz** [comment]
Hi @davidcsisk , I think this error occurs when the compilers do not match.

Can you confirm if you are using any of these:

1. Python x64 MSVC + MSVC x64
2. Python x32 MSVC + MSVC x32
3. Python x64 MingW + MingW x64
4. Python x32 MingW + MingW x32

My guess in this case is that Python was compiled for MSVC but Nim tries to use MingW (incompatible compilers). You can make sure by doing: `python --version` and it will say `(MSC)` instead of MSVC for some reason but MSC means "MSVC". If Python uses MSVC you won't be able to use MingW. You could install a MingW version of Python or install MSVC so that Nim (and therefore Nimporter) will use MSVC instead of MingW.

Let me know how it goes 🙂

**Comment by Pebaz** [comment]
Hi @scrazzz, no worries, the goal here is to make the C compiler used to compile Python match the C compiler used to compile the C output from Nim.

For instance, if your `python --version` mentions "MSC", you will have to have Microsoft Visual C++ compiler installed on your system so that the Nim compiler can auto discover it and use it to ultimately build your Nim module.

**Comment by scrazzz** [comment]
@Pebaz Thanks for the quick reply!

I do have Microsoft Visual C++ compiler installed. What's the next step?
![image](https://user-images.githubusercontent.com/70033559/206889103-2327bb6f-f687-4a65-8146-627fdc712b8f.png)

Additional:
python
![image](https://user-images.githubusercontent.com/70033559/206889036-b1706e3e-c070-450c-b966-0ac4878e4516.png)

**Comment by davidcsisk** [comment]
Hi...I'm not sure I fully understand the question.  @Pebaz , here's my output:

C:\Users\david>python --version
Python 3.9.8

No MSVC mentioned.  Does this get you what you needed?

Thanks and regards,
Dave

**Comment by scrazzz** [comment]
@davidcsisk `python --version` won't output the required info. Just open the Python REPL by running `python` in your cmd application.

**Comment by mukherjee** [comment]
> @davidcsisk `python --version` won't output the required info. Just open the Python REPL by running `python` in your cmd application.

@davidcsisk As scrazzz mention `python --version` won't work. The correct command is actually:
`python -VV`

**Comment by Pebaz** [comment]
Shoot sorry, my bad yeah opening the prompt is usually how I check that (made a bad guess). Thanks @mukherjee for the alternate way of checking. @davidcsisk have you had an opportunity to run that command?

We should be able to get to the bottom of this, I’ve seen this sort of issue happen a lot during project setup but let’s figure it out 😀

**Comment by Pebaz** [comment]
Closing this for now but if anyone still needs help with dev env setup let me know.
